services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "30001:30001"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - "30002:30001"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:6
    container_name: mongo3
    ports:
      - "30003:30001"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-init:
    image: mongo:6
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster
    entrypoint: >
      bash -c "
      sleep 10 &&
      mongosh --host mongo1 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:30001\", priority: 2 },
            { _id: 1, host: \"mongo2:30001\", priority: 1 },
            { _id: 2, host: \"mongo3:30001\", priority: 1 }
          ]
        })
      '
      "

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongo-cluster:
    driver: bridge
